AWSTemplateFormatVersion: "2010-09-09"

Description: Create Storage Config IAM Role

Parameters:
  IamRoleName:
    Description: Storage Config IAM Role Name
    Type: String
  DatabricksAccountIDParam:
    Description: Databricks Account ID
    Type: String
  BucketNameParam:
    Description: Ref Bucket Name
    Type: String

Resources:
  IamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName : !Ref IamRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - {Effect: "Allow", Principal: {AWS: ["arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL", !Sub "arn:aws:iam::${AWS::AccountId}:role/${IamRoleName}"]},Action: "sts:AssumeRole",Condition: {StringEquals: {"sts:ExternalId": !Ref DatabricksAccountIDParam}}}
  
  IAMPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: !Sub "${IamRoleName}-policy-1"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - {"Action":["s3:GetObject","s3:PutObject","s3:DeleteObject","s3:ListBucket","s3:GetBucketLocation"],"Resource":[ !Sub "arn:aws:s3:::${BucketNameParam}-${AWS::AccountId}'/*",!Sub "arn:aws:s3:::${BucketNameParam}-${AWS::AccountId}"],"Effect":"Allow"}
          - {"Action":["kms:Decrypt","kms:Encrypt","kms:GenerateDataKey*"],"Resource":["*"],"Effect":"Allow"}
          - {"Action":["sts:AssumeRole"],"Resource":[!Sub "arn:aws:iam::${AWS::AccountId}:role/${IamRoleName}"],"Effect":"Allow"}
      Roles:
        - !Ref IamRole

Outputs:
  storageConfigIamRole:
     Description: The IAM Role Arn
     Value: !Sub '${IamRole.Arn}'
     Export: {Name: !Sub '${AWS::StackName}-IamRole'}